#apiVersion: v1
#kind: Namespace
#metadata:
#  name: cert-manager-test
#---
#apiVersion: cert-manager.io/v1alpha2
#kind: Issuer
#metadata:
#  name: test-selfsigned
#  namespace: cert-manager-test
#spec:
#  selfSigned: {}
#---
#apiVersion: cert-manager.io/v1alpha2
#kind: Certificate
#metadata:
#  name: selfsigned-cert
#  namespace: cert-manager-test
#spec:
#  dnsNames:
#    - example.com
#  secretName: selfsigned-cert-tls
#  issuerRef:
#    name: test-selfsigned
#
---
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: grpc-test-selfsigned
  namespace: grpc-test
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: testing-grpc
  namespace: grpc-test
spec:
  dnsNames:
    - testing-grpc
  secretName: testing-grpc-tls
  issuerRef:
    name: grpc-test-selfsigned